spring:
  application:
    name: cadastro

  # =============================
  # CONFIGURAÇÃO DO BANCO H2
  # =============================
  h2:
    console:
      enabled: true          # Habilita o console H2 no navegador
      path: /h2-console      # Caminho para acessar o console

  datasource:
    url: jdbc:h2:file:./data/banco   # Usa arquivo físico (persiste dados)
    driver-class-name: org.h2.Driver
    username: admin                  # Usuário do banco
    password: 1234                   # Senha do banco

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true                   # Mostra os comandos SQL no console
    properties:
      hibernate:
        format_sql: true             # Formata o SQL de forma legível
